import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { TiArrowBackOutline } from "react-icons/ti";
import Rating from "../components/Rating";
import { useState } from "react";

export default function RatingAaplikasi() {
  const router = useRouter();
  const [mudah, setMudah] = useState(0);
  const [lengkap, setLengkap] = useState(0);
  const [bantu, setBantu] = useState(0);
  const handleSubmit = () => {
    console.log("submit");
  };
  return (
    <div className="relative flex flex-col h-screen md:px-[18%] overflow-hidden bg-gray-200 ">
      <Head>
        <title>Distribusi Konten Digital UNDIPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center text-white justify-between px-4 py-2 bg-gray-700">
        <h1 className="text-xl font-semibold">Rating Aplikasi</h1>
        {/* action menu */}
        <div className="relative inline-block text-left">
          <button
            className="p-2 rounded-full bg-gray-300 bg-opacity-5"
            onClick={() => router.back()}
          >
            <TiArrowBackOutline className="text-lg" />
          </button>
        </div>
      </div>
      <div className="px-4 py-2 bg-gray-100 h-full">
        <div className="mb-2">
          Menurut anda, apakah aplikasi ini mudah Diakses?
          <Rating
            leftText="Sangat Mudah"
            rightText="Sangat Sulit"
            value={lengkap}
            setValue={setLengkap}
          />
        </div>
        <div className="mb-2">
          Apakah konten yang tersedia di aplikasi ini sudah lengkap?
          <Rating
            leftText="Sangat Tidak Lengkap"
            rightText="Sangat Lengkap"
            value={bantu}
            setValue={setBantu}
          />
        </div>
        <div className="mb-2">
          Apakah anda merasa terbantu dengan adanya aplikasi ini?
          <Rating
            leftText="Tidak Terbantuh"
            rightText="Sangat Terbantuh"
            value={mudah}
            setValue={setMudah}
          />
        </div>
        <button
          disabled={[mudah, lengkap, bantu].includes(0)}
          className={`${
            [mudah, lengkap, bantu].includes(0) ? "bg-gray-400" : "bg-blue-500"
          } flex items-center rounded-md justify-center text-white p-1 px-6 w-fit`}
          onClick={handleSubmit}
          // onClick={() => download(newPath, newPath.replace("/img/", ""))}
        >
          Kirim
          {/* <HiUpload className="text-lg ml-1" /> */}
        </button>
      </div>
    </div>
  );
}
